name: Continuous Integration & Deployment

on:
  push:

jobs:
  fmt-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install Node
        uses: volta-cli/action@v4

      - name: Select Rust Version
        run: cargo --version

      - name: Install deps
        run: npm ci

      - name: Format Check
        run: npm run fmt-check

  spell:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install Node
        uses: volta-cli/action@v4

      - name: Install deps
        run: npm ci

      - name: Spell Check
        run: npm run spell

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install Node
        uses: volta-cli/action@v4

      - name: Select Rust Version
        run: cargo --version

      - name: Ensure Rust Target is installed
        run: rustup target add wasm32-unknown-unknown

      - name: Install deps
        run: npm ci

      - name: Lint Check
        run: npm run lint

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install Node
        uses: volta-cli/action@v4

      - name: Select Rust Version
        run: cargo --version

      - name: Ensure Rust Target is installed
        run: rustup target add wasm32-unknown-unknown

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build -- --base-href /${{ github.event.repository.name }}

      - name: Upload Github Pages Artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v4
        with:
          path: ${{ github.workspace }}/dist/rezepte.ttst.de/browser

  deploy:
    if: github.ref == 'refs/heads/main'

    # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    needs: build

    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
